name: Sync Google Scholar Publications

on:
  schedule:
    - cron: '0 0 * * 0'  # every Sunday
  workflow_dispatch:     # allows manual trigger

jobs:
  update-publications:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install scholarly
        run: |
          pip install scholarly pyyaml

      - name: Fetch and write publications
        run: |
          python scripts/fetch_publications.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add _data/publications.yml
          git commit -m "Update publications from Google Scholar"
          git push

